application: tweetement0
version: master
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
