application: tweetement0
version: master
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /
  static_files: index.html
  upload: index.html

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /queue/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest

- name: webapp2
  version: latest
